branch-defaults:
  production:
    environment: closing-bell-prod
  development:
    environment: closing-bell-dev
global:
  application_name: closing-bell
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
